[build]
  base = "client"
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[context.production.environment]
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"
